---

- name: cat diffs_file
  debug:
    var: juniper_junos_config_result.diff_lines
  tags: snmp

- name: Pausing for user to review configuration changes for all hosts
  pause:
    prompt: "Please review configuration changes"
    seconds: 20
  tags: snmp

- name: Get TimeDateStamp
  set_fact:
    mydate: "{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
  tags: snmp

- name: Set build path
  set_fact:
    build_path_post: "build/{{ inventory_hostname }}/{{ mydate}}"
  tags: snmp

- name: Create subdirectory for storing configs and diffs
  file:
    path: "{{ build_path_post }}"
    state: directory
    mode: 0770
  tags: snmp

- name: create temporary file
  tempfile:
    state: file
    suffix: .set
  register: snmp_temp_file
  tags: snmp

- name: Build config snippet from template
  template:
    src: ../templates/snmp.j2
    dest: "{{ snmp_temp_file.path }}"
  tags: snmp

- name: Push SNMP config with commit confirmed
  juniper_junos_config:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    load: set
    src: "{{ snmp_temp_file.path }}"
    dest_dir: "{{ build_path_post }}"
    diff: true
    check: false
    commit: true
    confirmed: 10
    port: 22
    timeout: 60
  register: juniper_junos_config_result
  tags: snmp

- name: Delete temporary file for security reasons
  file:
    path: "{{ snmp_temp_file.path }}"
    state: absent
  tags: snmp

- name: checking diffs from pre and post commit
  command: diff -I SECRET-DATA {{ build_path_pre }}/{{ ansible_ssh_host }}.diff {{ build_path_post }}/{{ ansible_ssh_host }}.diff
  failed_when: "diff.rc > 0"
  changed_when: False
  register: diff
  tags: snmp

- name: Wait 10 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
    timeout: 30
  connection: local
  tags: snmp

- name: Issuing secondary commit to finalize changes
  juniper_junos_config:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    diff: false
    check: true
    commit: false
    port: 22
    timeout: 60
  tags: snmp
