---
- name: Get TimeDateStamp
  set_fact:
    mydate: "{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
  tags: snmp

- name: Set build path
  set_fact:
    build_path_pre: "build/{{ inventory_hostname }}/{{ mydate}}"
  tags: snmp

- name: Create subdirectory for storing configs and diffs
  file:
    path: "{{ build_path_pre }}"
    state: directory
    mode: 0770
  tags: snmp

- name: create temporary file
  tempfile:
    state: file
    suffix: .set
  register: snmp_temp_file
  tags: snmp

- name: Build config snippet from template
  template:
    src: ../templates/snmp.j2
    dest: "{{ snmp_temp_file.path }}"
  tags: snmp

- name: Push SNMP config without committing so user can review
  juniper_junos_config:
    user: "{{ device_username }}"
    passwd: "{{ device_password }}"
    load: set
    src: "{{ snmp_temp_file.path }}"
    dest_dir: "{{ build_path_pre }}"
    diff: true
    check: true
    commit: false
    port: 22
    timeout: 60
  register: juniper_junos_config_result
  tags: snmp

- name: Delete temporary file for security reasons
  file:
    path: "{{ snmp_temp_file.path }}"
    state: absent
  tags: snmp

- name: proceed with config changes if needed
  import_tasks: commit_confirmed_tasks.yml
  when: juniper_junos_config_result|changed
  tags: snmp
