---
- name: Get TimeDateStamp
  set_fact: mydate="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
- name: Deploy Junos config to device
  junos_install_config:
    file: roles/snmp/files/snmp.set
    diffs_file: "{{ inventory_hostname }}-{{ mydate }}-config.diff"
    host: "{{ inventory_hostname }}"
    replace: yes
    user: "{{ username }}"
    passwd: "{{ password }}"
    timeout: 60
